### PR TITLE
Fix credo errors

### PR DESCRIPTION
**Pull request by SimonLab**
ref: #11

### CODE REVIEW

**Comment by nelsonic** [comment]
@SimonLab please `try` re-basing this branch on `master` and see if Travis-CI passes. thanks! 👍

**Comment by SimonLab** [comment]
Finally manage to fix the tests for this PR and credo is happy too
image

**Comment by SimonLab** [comment]
Running `mix credo --strict` still returns some error:
image

I'll try to fix these two!

**Comment by SimonLab** [comment]
This PR should be now ready for review. `mix credo --strict':
image

**Review by nelsonic — APPROVED** [review]
@SimonLab credo fixes look good. thanks. 
(_Please assign when you feel it's ready to merge_)

**Comment by nelsonic** [comment]
Thanks @SimonLab 👍

**Pull request merged**
